pipeline {
    agent any
    stages {
        stage('test') {
            agent { dockerfile 'FilRouge/backend/Jenkinsfile' }  
            stages {
                stage('Test') {
                    steps {
                        sh 'docker --version'
                    }
                }
            }
        }
    }
}
