pipeline {
    agent any
    environment {
        DOCKER_COMPOSE_FILE = 'FilRouge/backend/docker-compose.yaml'
    }
    stages {
        stage('List Files') {
            steps {
                sh 'ls -la FilRouge/backend'
            }
        }
        stage('Build Dockerfile') {
            steps {
                script {
                    // Construire l'image Docker en utilisant le Dockerfile dans le bon répertoire
                    def customImage = docker.build('python:3.12.2', 'FilRouge/backend')
                }
            }
        }

          stage('Build Docker Compose ') {
            steps {
                script {
                    if (!fileExists('FilRouge/backend')) {
                        error "Le répertoire 'FilRouge/backend' est introuvable."
                    }
                    sh 'docker-compose -f ${DOCKER_COMPOSE_FILE}  up --build -d'
                }
            }
        }
        stage('Run Tests') {
            steps {
                sh 'docker-compose -f ${DOCKER_COMPOSE_FILE}  run test'
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker-compose -f ${DOCKER_COMPOSE_FILE} down'
            }
        }
        post {
            failure {
                echo 'Une erreur est survenue pendant le pipeline.'
            }
            always {
                echo 'Pipeline terminé.'
            }
        }
    }
}

