pipeline {
    agent any
    environment {
        DOCKER_COMPOSE_FILE = 'FilRouge/frontend/docker-compose.yaml'
    }
    stages {
        stage('List Files') {
            steps {
                // Liste les fichiers du répertoire
                sh 'ls -la FilRouge/frontend'
                sh 'cat ${DOCKER_FILE} '
            }
        }
        stage('Build Docker') {
            steps {
                script {
                    // Vérifie si le répertoire existe
                    if (!fileExists('FilRouge/frontend')) {
                        error "Le répertoire 'FilRouge/frontend' est introuvable."
                    }
                    // Lance le build avec docker-compose
                    sh 'docker compose -f ${DOCKER_COMPOSE_FILE} up --build -d'
                    sh 'docker images'
                }
            }
        }
       stage('Push Image Docker - Production') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'dockerhub', variable: 'dockerhub_pwd')])  {
                        sh 'docker login -u evandiaye -p ${dockerhub_pwd}'
                    }

                    // Commit - container - images 
                    sh 'docker container ls'
                    sh 'docker container commit frontend-nginx-1 nginx'
                    
                    // Ajouter un tag à l'image avant le push
                    sh 'docker image tag nginx:stable-alpine evandiaye/ nginx:stable-alpine'
                    // Pousser l'image taguée
                    sh 'docker image push evandiaye/nginx:stable-alpine'

                }
            }
        }
        
        stage('Cleanup') {
            steps {
                // Arrête et nettoie les conteneurs, réseaux et volumes
                sh 'docker compose -f ${DOCKER_COMPOSE_FILE} down'
            }
        }
        
    }
    post {
        failure {
            echo 'Une erreur est survenue pendant le pipeline.'
        }
        always {
            echo 'Pipeline terminé.'
        }
    }
}
