pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    docker.image('node:22.13.0-alpine3.21').inside {
                        // Steps inside the Docker container
                        sh 'npm install'
                    }
                }
            }
        }
    }
}
