pipeline {
    agent: any
    stages {
        stage('Build') {
            agent { backend/Dockerfile true }
            steps {
                sh 'node --version'
                sh 'svn --version'
            }
        }
    }
}
